### ISSUE TITLE
Picturefill not working on Firefox 38.0.1 on Mac

### ISSUE THREAD

**Issue by Jobkooi** [scottjehl/picturefill#504] opened 2015-05-31 11:54 UTC
Hello,

I've recently completed my site and implemented a very basic use of the picturefill polyfill. This worked fine, and it's great to be able to use picturefill, a Big Thank You for that!

However, I ran into an issue which seems to be related with the new release of Firefox, v. 38.0.1 for Mac. The new version installed without me realizing the 'silent' upgrade and caused the images to not resize anymore. 

In FF 38.0.1 only the smallest of the 3 defined sizes shows, in FF 37.0.2 picturefill works just fine. As said, this is on a Mac.I've used Picturefill - v2.3.1 - 2015-04-09 and my site is at www.levenskrachten.be

Reinstalling FF 37.0.2 solved the problem, but ofc this isn't the solution... I don't know if this is picturefill or the srcset implementation in FF 38.0.1 but I thought I'd let you know....

Thanks,
Job

**Comment by jegtnes** [comment] 2015-05-31 13:32
Hey @jobkooi,

This is a known issue in Firefox 38 and is scheduled to be fixed in Firefox
39.

If you need this behaviour to be patched before then you can use this
script:
https://github.com/scottjehl/picturefill/blob/afarkas-pf3-proposal/src/plugins/gecko-picture/pf.gecko-picture.js

(duplicate of #501)

Hope this helps!

**Closed** 2015-05-31 13:34 UTC

**Comment by aFarkas** [comment] 2015-05-31 16:40
@Jobkooi 
Your markup is invalid. There is no *%* unit allowed in ``sizes``, use ``sizes="100vw"`` instead.

Beside this, it seems to be a FF issue. In case *%* is used the browser should fallback to *100vw* anyway. While this is done with any other invalid ``sizes`` value, it is not with *%*. In case this is not known, someone can/should file an issue.

**Comment by Jobkooi** [comment] 2015-06-01 06:39
Hi @aFarkas,
 
Thank you for pointing out the invalid markup. I changed it to <code>sizes="100vw"</code> and now it works just fine in FF 38.0.1

Thanks!
