### ISSUE TITLE
Inconsistent behaviour while failing (tested in chrome)

### ISSUE THREAD

**Issue by AoDev** [scottjehl/picturefill#459] opened 2015-03-18 12:18 UTC
Hello, 

I don't understand this bad behaviour. I can't say much about it because there is no error in console.
So I have made a small screencast here:
http://youtu.be/ZW6UqD-G6nw

This is chrome 41. 
You can see the site at http://kevinpurnelle.com

Any idea, what more can I investigate to add to this issue?

**Comment by jegtnes** [comment] 2015-03-18 12:46
Hey @AoDev,

Chrome 41 supports responsive images by default, so Picturefill shouldn't even be executing in Chrome. What happens if you remove Picturefill? Does this happen in other browsers? If you keep your network tab open and reload until the image doesn't load, does the image load, time out, or not appear in Network at all?

**Comment by AoDev** [comment] 2015-03-18 19:16
Actually I started to test it in chrome because it was failing on my mobile. Android 4.4.4, default android browser and had the same kind of behaviour.

Regarding desktop, I have tried what you said.

Chrome without polyfill : does not fail
Chrome with polyfill: fail sometimes the same way than in the screencast.

Firefox: seems to work correctly with the polyfill
Safari: seems to work correctly with the polyfill

**Comment by mike-engel** [comment] 2015-03-18 21:59
@AoDev Are you using picturefill 2.2 or 2.3.0-beta?

**Comment by AoDev** [comment] 2015-03-18 22:12
@mike-engel This is  Picturefill - v2.2.1 - 2015-02-03

**Comment by AoDev** [comment] 2015-03-18 22:22
I have been playing around with it and somehow it seems that the picture element shim may be involved in that problem, is it possible? 

    <script> document.createElement( "picture" ); // Picture element HTML5 shiv </script>

If I don't include picturefill but leave the picture element shim, this still causes this bad behaviour.
If I remove both, then it seems to be ok.

**Comment by aFarkas** [comment] 2015-03-19 12:00
@AoDev 
I just played around with your information and I can confirm the behavior. It seems that the combination of the ``createElement`` shiv and the broken/invalid/broken data uri is causing this bug in Chrome (so for you it is simple to workaround it by using a valid data uri).

Here is a simplified testcase:
http://jsfiddle.net/1gnrwLvy/1/

Do you want to file a [chrome issue](https://code.google.com/p/chromium/issues/list) and link it here in this issue?

If not, just let me know, so I can report this bug. ping @yoavweiss

**Comment by AoDev** [comment] 2015-03-19 13:29
@aFarkas Thanks for investigating and for the fiddle.

I didn't know that my data:uri image wasn't right. I found it here:
http://stackoverflow.com/questions/9126105/blank-image-encoded-as-data-uri
It's one of the answers. (it seemed to work fine)

You can create the chrome issue.

Btw, maybe a broken image would cause the same problem, even if it's not provided as a data-uri? I'll test when I have time.

**Comment by mike-engel** [comment] 2015-03-19 21:54
Closing this since this seems to be a chrome issue. Let us know if it's not, and we can re-open this issue.

**Closed by mike-engel** 2015-03-19 21:54 UTC

**Comment by aFarkas** [comment] 2015-03-20 12:06
https://code.google.com/p/chromium/issues/detail?id=469131
