### ISSUE TITLE
Picturefill v3 alpha IE8 error

### ISSUE THREAD

**Issue by ritchieanesco** [scottjehl/picturefill#542] opened 2015-07-14 02:41 UTC
Hey guys,

Getting a  'Object deosnt support this property or method' on IE8. When debugging it's pointing to a function named 'teardownRun'.

cheers,
Ritch

**Comment by mike-engel** [comment] 2015-07-14 14:08
@ritchieanesco Which version of picturefill are you using?

**Comment by aFarkas** [comment] 2015-07-14 17:12
@ritchieanesco 
It seems that you use 3.0, I heavily tested the code in IE8 and can not reproduce this. Do you monkey patch/duck punch picturefill or picturefill._?

It is very important that we get a testcase here. Not if this is to heavy to produce, it would be good enough if you would give me a link or a zipped version of your prototype.

**Comment by ritchieanesco** [comment] 2015-07-14 22:02
@aFarkas no monkey patching, we are initialising the script via requirejs and the error comes on page load, however it seems intermittent.

**Comment by aFarkas** [comment] 2015-07-15 05:35
@ritchieanesco 
I think, I fixed your IE8 issue (Still can't reproduce, but remembered something weird IE8 is doing). Beside this error in the console. picturefill should just work fine. Please try the following branch: https://github.com/scottjehl/picturefill/tree/issue-542/dist

The fix itself is this:
https://github.com/scottjehl/picturefill/commit/79f4db48f86ec88b275b10f3ad1b377145ca755a

**Comment by ritchieanesco** [comment] 2015-07-15 12:15
Picturefill still worked fine after the error. I could have possibly had 2 instances of Picturefill running, as it was required in from one module. Not sure if that would be the cause. Since i've removed the additional picturefill require i am yet to see that error in the console.

**Comment by mike-engel** [comment] 2015-07-15 14:47
@ritchieanesco Alright, I'm gonna close this issue then since it seems fixed. If I've read that wrong, please let us know and we'll re-open this issue. Thanks!

**Closed by mike-engel** 2015-07-15 14:47 UTC
Labels: Critical, Needs info
