### ISSUE TITLE
Firefox 41 | naked img srcset continues to not react to resize/viewport changes

### ISSUE THREAD

**Issue by rjgotten** [scottjehl/picturefill#586] opened 2015-10-08 12:17 UTC
Firefox 41.0.1 Windows continues to require a full F5 refresh for `srcset` on a naked (not wrapped inside a `<picture>`) element to have any effect.

This can easily be seen in (non-)action on the http://scottjehl.github.io/picturefill/examples/demo-01.html example and is already reported on Bugzilla as https://bugzilla.mozilla.org/show_bug.cgi?id=1166138

The UA sniffing that is put in place as a guard around the workaround logic should be expanded to cover FF 41 in the case of naked `<img>` elements

**Comment by aFarkas** [comment] 2015-10-09 17:49
@rjgotten 
Thanks for your bug report. We will certainly do something about it. Changing just the version to 41 won't help here. The bug isn't fixed yet, which means, that there won't be a fix for 43 for sure.  (Actually it's quite probably, that 46-50 won't be patched either).

At the end, I don't see this as a big issue though.

**Comment by aFarkas** [comment] 2015-10-13 18:46
So what do you think we should do with this bug. The more I think about it the more I don't want to fix this.

The FF behavior is indeed undesirable, but it is technically not a bug/spec violation (different to the situation with `picture`), we don't have so many "resizing" users and it is quite heavy to feature detect.

I think, if we want to fix it, we have the following options:

1. Use a higher version number (i.e.: 45) and hope it is fixed until then
2. Remove the version number entirely and give FF the pain to run this script even if this bug was fixed.

**Comment by mike-engel** [comment] 2015-10-13 18:52
Two seems the most future-proof. Once we know it's fixed, we can then edit the version number.

**Comment by rjgotten** [comment] 2015-10-14 07:47
Personally, I'd go for the unmentioned option 3: remove the version number check until FF fixes this, then re-introduce it in a hotfix release of picturefill when the cut-off point is known.

**Comment by aFarkas** [comment] 2015-10-14 09:19
@rjgotten 
This is option two. Of course we will change the code, if we know more. But we can't expect that anybody will update.

**Comment by mike-engel** [comment] 2015-10-22 20:07
Closed, as this has been merged into 3.0 and should be released soon.

**Closed by mike-engel** 2015-10-22 20:07 UTC
