### ISSUE TITLE
No Image Download in FireFox 38

### ISSUE THREAD

**Issue by starlingDesign** [scottjehl/picturefill#503] opened 2015-05-28 15:23 UTC
I am using the picture element and srcset in an unusual way, but should work.

The HTML
```html
<picture>
	<!--[if IE 9]><video style="display: none;"><![endif]-->
	<source srcset="images/imgWelcome-hoopHouseRasperries.jpg, images/imgWelcome-hoopHouseRasperries_x2.jpg x2" media="(min-width: 825px) and (max-width: 63.5em)" />
	<!--[if IE 9]></video><![endif]-->
	<img alt="" />
</picture>
```
Basically, I have an image place holder, it's empty, so nothing downloads by default.  This particular image is simply visual filler. (replaces a logo that moves to the header for medium screens)

In Chrome 43, Opera 23, Safari 5.1 everything works as expected, there is no image downloaded unless in the specified screen size, and the image downloads/displays when re-sizing the browser window. (in Chrome Canary 45 all the source images download regardless)

The problem is with FireFox 38, when resizing the browser window, (from a size that the image does not show) the image will not download.  If the page is loaded within the size requirement, it will  download. (and thus show/hide as necessary)

**Comment by Wilto** [comment] 2015-05-28 15:25
Duplicate of #501

This is a bug with the native `picture` implementation that landed in FF38, and should be solved by 39:
https://bugzilla.mozilla.org/show_bug.cgi?id=1135812

We do have a stand-alone fix for this issue, though: https://github.com/scottjehl/picturefill/blob/afarkas-pf3-proposal/src/plugins/gecko-picture/pf.gecko-picture.js

Hopefully that does the trick; let us know if not.

**Closed by Wilto** 2015-05-28 15:25 UTC
