### ISSUE TITLE
Chrome not loading correct images

### ISSUE THREAD

**Issue by sh1fty** [scottjehl/picturefill#319] opened 2014-08-27 20:37 UTC
Chrome 36.0.1985.135 on Android is not switching out images at all, it's only using the last defined src from the srcset.

**Comment by sven-tappert** [comment] 2015-02-26 21:10
This might be no bug. 

I don't know if this applies to Chrome 36 on Android, but Chrome 40 supports IMG-Tags with *srcsets* & *sizes* attributes natively, so picturefill might not be active at all. 

And Chrome (now) has a little modified implementation: it only exchange images when HIGHER resolution src is required. As soon as an image with a high resolution is in cache, it won't change back to low res src. This produces strange results while testing but seems to be very reasonable. 

Also see answer of Alexander Farkas in:
http://stackoverflow.com/questions/28155861/google-chrome-version-40-srcset-attribute-problems

I think it would be useful to imitate this behaviour in picturefill as well, since it could help to prevent unnecessary double loading of images even on initial page load.

**Comment by elHornair** [comment] 2015-04-21 08:24
Are there any news on this?
Something that might be related: Google's PageSpeed Insights seems to always load the biggest image of a srcset on an image tag (see https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fscottjehl.github.io%2Fpicturefill%2Fexamples%2Fdemo-01.html). Is it save to assume, that PageSpeed Insights just cached the bigger image and these warnings can be ignored?

**Comment by aFarkas** [comment] 2015-04-21 11:04
@elHornair 
I don't think this here is a bug or a problem with picturefill. It is simply a very poor example of our demos. 

The largest image in our ``srcset`` has a width of 768 pixel, if the viewport is 320 on a 2x device we need 640px. Due to the fact that the next lower candidate is 480, we choose the 768 image.

**Comment by elHornair** [comment] 2015-04-21 13:29
@aFarkas You are right of course - Sorry for my confusion :)

**Comment by aFarkas** [comment] 2015-04-21 13:50
Well, the demo is confusing. PR's are always welcome!

**Comment by mike-engel** [comment] 2015-05-29 22:14
Closing this issue as it's not a bug.

**Closed by mike-engel** 2015-05-29 22:14 UTC
