### ISSUE TITLE
`teardownRun` causes an error on IE8

### ISSUE THREAD

**Issue by verlok** [scottjehl/picturefill#552] opened 2015-07-22 13:55 UTC
Hi there,
the command `pf.teardownRun( options );` at line 210 of picturefill 3.0.0 beta throws the following error on IE8: 

**Object doesn't support property or method 'teardownRun'**

Is IE8 supported in v3.0.0?

**Comment by aFarkas** [comment] 2015-07-22 14:05
@verlok 
This error should happen (sometimes and then) only once, but all images should be polyfilled right in IE8, am I right with my assumption?

Yes picturefill 3.0 supports IE8. About your special error. I have a [fix for it here](https://github.com/scottjehl/picturefill/tree/issue-542/dist). We haven't merged it, because I couldn't reproduce this error.

In case you can reproduce this error and can confirm that it is fixed indeed, we will merge it ASAP of course.

**Comment by verlok** [comment] 2015-07-22 14:13
Hi @aFarkas, you can reproduce it opening [this page](http://verlok.github.io/img_srcset_lazyload/index_pf3.html) in IE8.

**Closed** 2015-07-27 11:14 UTC
