### ISSUE TITLE
Add automated cross-browser testing

### ISSUE THREAD

**Issue by nathanaeljones** [scottjehl/picturefill#418] opened 2015-01-19 17:49 UTC
Maintaining cross-browser compatibility is impossible without an automated test suite that runs on said browsers. 

Both BrowserStack and SauceLabs will offer free OSS accounts to the maintainers if asked.

I set this up for [slimmage.js](https://github.com/imazen/slimmage); feel free to re-use any and all files or bits you find useful. 

I'm new to selenium testing, but I may be able to help on some of the issues.

**Comment by mike-engel** [comment] 2015-06-10 04:24
Dupe of #489.

**Closed by mike-engel** 2015-06-10 04:24 UTC
