### ISSUE TITLE
double download in iOS?

### ISSUE THREAD

**Issue by HelKyle** [scottjehl/picturefill#563] opened 2015-08-10 04:15 UTC
I have use Develop Tool of Safari to look in for,what I found is it still double download. why?
add...
I don't use src attribute on img

**Comment by jegtnes** [comment] 2015-08-10 08:01
Good morning, @HelKyle!

Can you show us a reduced test case of what is triggering a double download? Also, which version of iOS Safari are you emulating, and which version of Picturefill are you on?

Thanks!

**Comment by aFarkas** [comment] 2015-08-10 09:17
You might want to read this (see last pattern): https://github.com/scottjehl/picturefill/issues/536

In case you are using lazyloading. You can also add this plugin: https://github.com/aFarkas/lazysizes/blob/gh-pages/plugins/fix-ios-sizes/fix-ios-sizes.js

**Comment by HelKyle** [comment] 2015-08-10 16:03
Hi，@jegtnes
I use iPhone 5s ,iOS8.3

I write a demo like this : 
```html
	<picture>
		<!--[if IE 9]> <video style="display: none;"> <![endif]-->
		<source media="(min-width: 480px)" srcset="2.png">
		<!--[if IE 9]> </video> <![endif]-->
		<img srcset="1.png">
	</picture>
```
It work on my mac     
![image](https://cloud.githubusercontent.com/assets/9882649/9176134/207ca5e4-3fbc-11e5-81b1-225262882e18.png)   

while I found it double download when I open the page on my iPhone (and I use Safari Developer Tool)

![image](https://cloud.githubusercontent.com/assets/9882649/9176086/c901fd8c-3fbb-11e5-8c05-af14d0470c7b.png)

 Can you help me?
Good night.

**Comment by HelKyle** [comment] 2015-08-10 16:08
Thanks, @aFarkas 

It works for me.

But, without fallback img means my website can not  support IE9 , right?

**Comment by nazimjamil** [comment] 2015-08-11 09:52
I'm seeing the same issue as reported by @HelKyle. On iOS (8.4) the browser downloads two images, whereas desktop will only download one, the correct one.

**Comment by aFarkas** [comment] 2015-08-11 16:57
This should all work in ie9 (even in ie 8). The only problem with this pattern is that it does not work with android 2.3.

**Comment by HelKyle** [comment] 2015-08-12 02:41
@aFarkas Yeah! It also work in ie9, Thanks you very much~
Now, I have another question,what the code means?

```html
<!--[if IE 9]><video style="display: none;"><![endif]-->
	<source srcset="1.png 960w, 2.png 480w" sizes="(max-width: 1280px) 100vw, 1280px">
<!--[if IE 9]></video><![endif]-->
```

In ie 9 video display:none, right ? How it works?

**Comment by mike-engel** [comment] 2015-08-12 15:55
@HelKyle The IE conditional there is a small hack to get IE9 to support the `picture` element. You can read more about it here: https://scottjehl.github.io/picturefill/#ie9

**Comment by HelKyle** [comment] 2015-08-13 02:03
Thanks, @mike-engel

**Comment by aFarkas** [comment] 2015-08-21 17:56
Do we want to close this? This is a documentation thing and seems to be a duplicate of #536.

**Closed** 2015-08-22 14:27 UTC
