### ISSUE TITLE
Picturefill with Bootstrap modals causes unexpected image downloads

### ISSUE THREAD

**Issue by keithchu** [scottjehl/picturefill#619] opened 2016-01-05 02:02 UTC
I have two Bootstrap modals, each with an image inside that uses the `<picture>` element, with 5 sources that correspond to 5 different width breakpoints. Here are the repro steps:

1. Open the first modal – the appropriate source image is loaded.
2. Resize the browser to cross a breakpoint threshold — the appropriate source image is loaded for that breakpoint.
3. Close the modal.
4. Open the second modal — the appropriate source image is loaded.
5. Resize the browser to cross a different breakpoint threshold from step 2 — the appropriate source image is loaded for that breakpoint, AND the appropriate source image from the first modal is loaded for that breakpoint.

This continues for every untriggered breakpoint, and increases with every new modal.

Is there a way to unbind picturefill from an image when the modal is closed?

**Comment by jegtnes** [comment] 2016-01-05 09:03
Heya @keithchu, thanks for reporting this issue and the detailed reproduction steps. Can you provide us with a reduced test case and let us know which browsers you are seeing this issue on, as well as the version of Picturefill you're using, if it's not the latest (3.0.1)? If you do, we can have a dig around to see what's happening.

Cheers!

**Comment by keithchu** [comment] 2016-01-05 22:17
Sure @jegtnes, I'll try to throw one together later.

Chrome latest (47.0.2526.106, 64-bit) on El Capitan
Picturefill latest (3.0.1)

**Comment by keithchu** [comment] 2016-01-06 22:55
http://jsfiddle.net/catharsis/ts2bp7dm/

Here you go, @jegtnes. Reproduction steps:

1. Click "Open modal 1"
2. Confirm in Network tab that one image was sent (<size>-1.jpg).
3. Close modal with escape or shade click.
4. Click "Open modal 2"
5. Confirm in Network tab that one image was sent (<size>-2.jpg).
6. Resize the result pane to cross a breakpoint threshold at 200w/400w/600.
7. Confirm in Network tab that two images were sent (<next-size>-1.jpg, <next-size>-2.jpg).

I *may* have found the issue too. When I removed the IE conditional comments for IE9, I wasn't able to reproduce the bug.

**Comment by aFarkas** [comment] 2016-01-07 18:58
@keithchu
This not a picturefill issue. It is a chrome bug. I can confirm this issue with Chrome and Opera, but it seems to be fixed in 49.0.2615.0 canary (64-bit).

Can you please try chrome beta and canary? If it is fixed in canary we are fine. Otherwise we need to report it.

**Comment by aFarkas** [comment] 2016-01-07 19:03
BTW.: Can someone try this with firefox 45+.

**Comment by mike-engel** [comment] 2016-01-07 21:44
@aFarkas just tested in FF `45.0a2 (2016-01-07)` and it seems like it's working as intended.

**Comment by keithchu** [comment] 2016-01-25 18:09
@aFarkas Sorry, just saw these updates now. Will test later tonight.

**Comment by mike-engel** [comment] 2016-02-05 03:51
Hey @keithchu, any update? Thanks!

**Comment by jegtnes** [comment] 2016-05-16 18:18
Closing this one for now due to lack of updates—if this does resurface again @keithchu please feel free to re-open.

**Closed by jegtnes** 2016-05-16 18:18 UTC
Labels: Browser Bug, Needs info
