### ISSUE TITLE
img with "srcset" and sizes"

### ISSUE THREAD

**Issue by nonsponsored** [scottjehl/picturefill#238] opened 2014-05-13 20:37 UTC
Is anyone else seeing a difference in behavior of the 'img with "srcset" and sizes" attributes' example on http://scottjehl.github.io/picturefill/ when viewed on Windows and OS X?

The small version of the image isn't displayed in Chrome, Firefox, or Safari on OS X, but is displayed in Chrome, Firefox, and IE on Windows.

**Comment by mike-engel** [comment] 2015-05-29 22:04
@thomasplevy @nonsponsored Has this been fixed for you guys in picturefill 2.3 or the 3.0 beta?

**Comment by mike-engel** [comment] 2015-06-09 05:06
Closing this one out for now. If the issue is still around, let us know.

**Closed by mike-engel** 2015-06-09 05:06 UTC
